In [1]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com


In [2]:
import tensorflow as tf
print(tf.__version__)


2.15.0


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'Do it like a professional']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'Do it like a professional']

In [6]:
### Vocabulary size
voc_size=1000

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[258, 359, 428, 563], [258, 359, 428, 466], [258, 277, 428, 707], [922, 653, 174, 125, 691], [922, 653, 174, 125, 710], [895, 258, 555, 428, 654], [783, 179, 146, 174, 674]]


In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 258 359 428 563]
 [  0   0   0   0 258 359 428 466]
 [  0   0   0   0 258 277 428 707]
 [  0   0   0 922 653 174 125 691]
 [  0   0   0 922 653 174 125 710]
 [  0   0   0 895 258 555 428 654]
 [  0   0   0 783 179 146 174 674]]


In [10]:
## feature representation dimensions
dim=20


In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 20)             20000     
                                                                 
Total params: 20000 (78.12 KB)
Trainable params: 20000 (78.12 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
## 'Do it like a professional'
embedded_docs[6]

array([  0,   0,   0, 783, 179, 146, 174, 674])

In [14]:
model.predict(embedded_docs[6])

1/1 [==============================] - 0s 67ms/step


array([[-0.0011517 ,  0.01464841, -0.03173901,  0.02961453, -0.03275188,
         0.01063102, -0.00463648, -0.01327894,  0.04962827,  0.04621981,
        -0.03990717,  0.03388535, -0.00277557,  0.00507282,  0.01699081,
        -0.04361413,  0.01243081,  0.00514364, -0.02532518,  0.04083811],
       [-0.0011517 ,  0.01464841, -0.03173901,  0.02961453, -0.03275188,
         0.01063102, -0.00463648, -0.01327894,  0.04962827,  0.04621981,
        -0.03990717,  0.03388535, -0.00277557,  0.00507282,  0.01699081,
        -0.04361413,  0.01243081,  0.00514364, -0.02532518,  0.04083811],
       [-0.0011517 ,  0.01464841, -0.03173901,  0.02961453, -0.03275188,
         0.01063102, -0.00463648, -0.01327894,  0.04962827,  0.04621981,
        -0.03990717,  0.03388535, -0.00277557,  0.00507282,  0.01699081,
        -0.04361413,  0.01243081,  0.00514364, -0.02532518,  0.04083811],
       [ 0.04630465,  0.01805018,  0.01916717,  0.02991067, -0.00872049,
         0.0205923 , -0.01960801, -0.02962102, -

In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 35ms/step


array([[[-0.0011517 ,  0.01464841, -0.03173901, ...,  0.00514364,
         -0.02532518,  0.04083811],
        [-0.0011517 ,  0.01464841, -0.03173901, ...,  0.00514364,
         -0.02532518,  0.04083811],
        [-0.0011517 ,  0.01464841, -0.03173901, ...,  0.00514364,
         -0.02532518,  0.04083811],
        ...,
        [-0.03706098, -0.02126219, -0.02848649, ...,  0.04565923,
         -0.03348982, -0.0038837 ],
        [ 0.03629318, -0.0282285 ,  0.03240529, ...,  0.04474253,
         -0.00260606, -0.02051622],
        [ 0.03294872,  0.03702391,  0.02162531, ..., -0.0489864 ,
         -0.01599969, -0.04376079]],

       [[-0.0011517 ,  0.01464841, -0.03173901, ...,  0.00514364,
         -0.02532518,  0.04083811],
        [-0.0011517 ,  0.01464841, -0.03173901, ...,  0.00514364,
         -0.02532518,  0.04083811],
        [-0.0011517 ,  0.01464841, -0.03173901, ...,  0.00514364,
         -0.02532518,  0.04083811],
        ...,
        [-0.03706098, -0.02126219, -0.02848649, ...,  