In [1]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com


In [2]:
import tensorflow as tf
print(tf.__version__)


2.15.0


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'Do it like a professional']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'Do it like a professional']

In [8]:
### Vocabulary size
voc_size=1000

In [9]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[671, 256, 26, 282], [671, 256, 26, 374], [671, 835, 26, 684], [322, 193, 105, 203, 770], [322, 193, 105, 203, 455], [685, 671, 519, 26, 673], [499, 531, 943, 105, 484]]


In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 671 256  26 282]
 [  0   0   0   0 671 256  26 374]
 [  0   0   0   0 671 835  26 684]
 [  0   0   0 322 193 105 203 770]
 [  0   0   0 322 193 105 203 455]
 [  0   0   0 685 671 519  26 673]
 [  0   0   0 499 531 943 105 484]]
